### ISSUE TITLE
Ender IO Capacitors - Periodic halting of input/output

### ISSUE THREAD

**Issue by Tellik** [utoc/BBQBugs#1]
Situation has affected all EIO Capacitor levels, both in a multiblock structure or individually.

Periodically, at seemingly random intervals, the input/output limits of the capacitor will set themselves to 0. This issue has not happened to everyone that I've talked to. Waffle hasn't seemed to be affected by this.

Everytime this has happened, power has been sending and receiving in and out of the capacitors. Unsure if this will occur if the capacitor is not being powered.

**Comment by utoc** [comment]
And what did you do to fix the problem when it happened?

**Comment by Tellik** [comment]
The only thing you can do is, when you catch it, change it back to the input/output limit you want.

**Comment by utoc** [comment]
Tellik, can you confirm this is still an issue with the latest updates to EIO and EnderCore?

**Comment by utoc** [comment]
Resolved with latest update
