### ISSUE TITLE
Disconnects upon login 

### ISSUE THREAD

**Issue by utoc** [utoc/BBQBugs#14]
This is going to end up being a long term big to track down and fix. 

http://pastebin.com/raw/rwrbedC8

**Comment by utoc** [comment]
http://pastebin.com/rbQEmsE7

**Comment by Tellik** [comment]
During game, when I get the same disconnects as when logging in for the first time, I get the following error message:

[15:01:52] [Client thread/INFO]: [CHAT] Whoosh!

Sep 08, 2016 3:02:23 PM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException

[15:02:23] [Client thread/INFO] [journeymap]: Mapping halted in /home/deus/.bbqlauncher/instances/BBQSauce v2/minecraft/journeymap/data/mp/BBQ~Sauce/DIM0

I'm not sure why it doesn't throw an error or message when logging in disconnected, as opposed to teleportation disconnecting, but I'd like to think they're related.

**Comment by MrNinja93** [comment]
@utoc it may be caused by https://github.com/mezz/JustEnoughItems/issues/353  

Also been wondering what on earth was causing the timeout in my pack and resigned myself to not finding it (hoping the fix fixes it and was the cause)
