### ISSUE TITLE
Getting outside of the WorldBorder

### ISSUE THREAD

**Issue by DreiPixel** [utoc/BBQBugs#15]
it seems like it is possible do get outside of the WorldBorder with a nether portal but doing so will kill you

EDIT: apparently its how its supposed to be in Vanilla :V. The world border does no math in the nether so 5000 blocks in the overworld are 5000 blocks in the nether for the worldborder.

**Comment by utoc** [comment]
That's pretty much it. No fixing this one more than likely.

**Comment by utoc** [comment]
Confirmed, there is no fixing this, We'll have to make sure to warn new users about this unless someone comes up with another suggestion.
