### ISSUE TITLE
Mek Pipes

### ISSUE THREAD

**Issue by Tellik** [utoc/BBQBugs#16]
YAMI (Yet Another Mek Issue) - Mekanism pipes when set to none, will continue to allow flow.
![2016-09-07_19 59 23](https://cloud.githubusercontent.com/assets/6219444/18335650/d4a27274-7535-11e6-92a8-6adc4db07643.png)

As you can see in the first picture, this pipe is set to 'none' on the left tower.

![2016-09-07_19 59 27](https://cloud.githubusercontent.com/assets/6219444/18335657/e6b483e4-7535-11e6-83c0-05b137cf587b.png)

In the second picture, it continues to fill the tower with the brine coming from the ender tank, even though the pipe output is set to none.

This behavior has also been noticed on gas piping and other pipes when set to 'none', where it doesn't honor the pipe setting.

**Comment by utoc** [comment]
I'll have to get with Aiden about this but we'll reconfirm this is an issue AFTER we update to release 292.

**Comment by Tellik** [comment]
Issue appears to be resolved, single player world testing. Will close when verified in server.
