### ISSUE TITLE
Binder Composite requires Mek Sawdust, no other compatible ones

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#17]
It has -pulpWood and -dustWood in the OreDictionary description, but the Techreborn Saw Dust (-pulpWood and -dustSawDust) or the Forestry Wood Pulp (-pulpWood) don't work for the recipe.

**Comment by utoc** [comment]
This will be changed in the next update.

**Comment by utoc** [comment]
The recipe change has been made.
