### ISSUE TITLE
Mek Energy Cell -> ActAdd DisplayStand energy doubling?

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#18]
A Mekanism Energy Cube with full 600,000 RF managed to fill two of the ActAdd Display Stands up to 800,000 RF. 

Some conversion issue somewhere?

**Comment by utoc** [comment]
Confirmed but its not limited to the display stand.  What are you using to transfer power?

**Comment by Minithra** [comment]
A Mek Energy Cube, placed directly in contact with the Display Stand. 

I haven't noticed it until now, because I used EnderIO stirlings surrounded by multiple machines, so any power doubling went unnoticed.

**Comment by utoc** [comment]
Testing energy transfer:

Devices used in their order = Energy left in test sending block / Energy in receiving block

Energy Cube (800KRF)(All sides set output) -> Relay -> Stand = 320.6 / 800
Energy Cube (800KRF)(All sides set input) -> Relay -> Stand = 464.9 / 800
Energy Cube (800KRF)(All sides set output) -> Any tier Mek universal cable -> = Stand 0 / 800
Energy Cube (800KRF)(All sides set input) -> Any tier Mek universal cable -> = Does not transfer any energy
Energy Cube (800KRF)(All sides set output) -> Ender IO Energy Conduit -> Energy Cube = 0 / 800
Energy Cube (800KRF)(All sides set output) -> Relay -> Energy Cube = 319/800
Energy Cube (800KRF)(All sides set output) -> Stand = 340.4 / 800
Energy Cube (800KRF)(All side sets input) -> Stand = Does not transfer any energy
EnderIO Capacitor Bank (1000KRF) (Sides are automatic) -> Stand = 200/800
EnderIO Capacitor Bank (1000KRF)(Sides set input) -> Stand = Does not transfer any energy
EnderIO Capacitor Bank (1000KRF)(Sides set automatic) -> Relay -> Stand = 157.9/800 (Correct if accounting for 5% relay loss)
Energy Cube (800KRF)(All sides set output) -> Double Crusher = 769.7/60
Energy Cube (800KRF)(All sides set input) -> Double Crusher = Does not transfer energy
Energy Cube (800KRF)(All sides set output) -> Universal Cable -> Double Crusher = 737.4/60

So.  EnderIO and AA seem to transfer energy normally.  Mek and AA seem to transfer normally if including an EnderIO conduit or Mek universal cable.  Mek and AA directly next to each other do not transfer normally regardless of the target machine or if using AA relays.  Somehow AA and Mekanism do not respect each others accounting of RF received or sent.

@ellpeck Does this go to you or Aiden?  (Trying to save you the grief of a misplaced ticket :P)

Running AA r60 and Mek 290 dev (havent updated to r292 yet)

**Comment by Ellpeck** [comment]
I have no idea, but I know that Mekanism is pretty good at not being able to fix its bugs, so I'm just going to wait a bit until I concider Mekanism properly working.

**Comment by utoc** [comment]
UPDATE: Its definitely Mekanism's implementation of Tesla.  Remove the Tesla.jar file and the issue goes away completely.

Now that EnderIO supports Tesla, the issue is present between Mek (as the energy provider) and EIO conduits sending to EIO capacitors or Mek's cells.
