### ISSUE TITLE
Weird crashes

### ISSUE THREAD

**Issue by Tellik** [utoc/BBQBugs#19]
I'm not sure exactly what's causing this. The first one happened randomly. Thought it was a one time thing.

Then after the scheduled restart, the other two happened immediately after logging in.
[crash-2016-09-08_11.50.26-client.txt](https://github.com/utoc/BBQBugs/files/464322/crash-2016-09-08_11.50.26-client.txt)
[crash-2016-09-08_23.02.42-client.txt](https://github.com/utoc/BBQBugs/files/464320/crash-2016-09-08_23.02.42-client.txt)
[crash-2016-09-08_23.04.33-client.txt](https://github.com/utoc/BBQBugs/files/464321/crash-2016-09-08_23.04.33-client.txt)

**Comment by utoc** [comment]
All exutils crashes. Abandoned mod that doesn't respond to trouble tickets
unfortunately. Are you about to play?

**Comment by Tellik** [comment]
It cleared after those times and didn't happen anymore. Weirdly enough, it was with a ExU drum that was partially filled with Mek fluid, that was just floating as an item on the ground, during a server reboot.

If that was the cause sort of, then I doubt it'll come up much and I'll just deal with it when it happens.
