### ISSUE TITLE
Ender Tanks - Configuration Request

### ISSUE THREAD

**Issue by Tellik** [utoc/BBQBugs#20]
It took me a bit to figure out what AA BlockMisc:8 was. But concerning the recipe balances:

A large capacity upgrade costs 4 empowered diamonds and 4 ender pearls (along with a block of black quartz). A small capacity upgrade costs 4/5 end stone, 1/2 eye of enders and a little glass.

A large capacity upgrade gives 4k storage upgrade, while a small gives 2k. To fully upgrade using small upgrades only, requires only 64 eye of enders. (To be made into the correct item, also if my math is correct.)

1) Request that large capacity upgrades increase storage capacity in 32k increments. This is to account for the diamonds that require the high tier empowerer, as well as the the other materials. I'm still not sure if this would motivate me to use higher upgrades or lower upgrades, but I imagine there would be a better balance.

Next issue:

Pump upgrades are a variable of ender tank capacity. The default capacity of 4k limits tank output to 1k mb/t. A max capacity of 256k limits tank output to 3k mb/t.

2) Request that capacity limits increase past 256k limit to allow for higher tank outputs. This will keep it inline with Mek piping sizes but also allow a full input into a brine thermal tower which requires 3k mb/t of water.

**Comment by utoc** [comment]
Pump upgrades have been maxed out to 8 from 4
Large upgrades have been increased to 16 from 4
