### ISSUE TITLE
Glass shard overlap between Quark and Terraqueous

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#21]
When breaking glass blocks, both the Quark Quark:glass_shards (#5734/0) and Terraqueous  terraqueous:item_main (#6436/108) types of glass shards drop. I'm assuming 1-4, based on limited testing. 

You only need 4 of each to make 1 glass block, so this is a way of duping glass :D 

The Quark shards seem to be split based on the glass color, while terraqueous has two tiers of shards (base one that drops smelts into 1 pane, and 4 can be crafted into the tier 2 shard, which smelts into one block).

**Comment by utoc** [comment]
Disabled in terraqueous  Thanks for the report!
