### ISSUE TITLE
Storage Network & Soul viles

### ISSUE THREAD

**Issue by Shadow3641** [utoc/BBQBugs#23]
Once you put a "Soul Vile" from Ender IO into a Storage Network System (i'm only using the "Item Box" from the Storage Network mod to store items in) you can not get it back out using the "Item Request Table" or the "Item Advanced Wireless Accessor". I have not tried the "Item Wireless Accessor".

**Comment by Shadow3641** [comment]
you can add the "Common Tartaric Gem(#4476/2)" to this list it did not have any will in it. The Petty and the Lesser work fine

**Comment by utoc** [comment]
I'll be around tomorrow to work on this. What time do you think you'll be
about?

**Comment by Shadow3641** [comment]
sorry been at work most of the week i will be home tonight or saturday

**Comment by Minithra** [comment]
Using Drawers as the storage medium, I can store/retrieve Soul Vials through the Item Request Table and the Advanced Wireless Accessor.

**Comment by utoc** [comment]
@Shadow3641 Can you try your RS terminal again and see if you can remove the items?  Might have been fixed in the update

**Comment by utoc** [comment]
https://github.com/MrRiegel/Storage-Network/issues/86

On-hold until developer responds

**Comment by utoc** [comment]
https://github.com/MrRiegel/Storage-Network/issues/82
