### ISSUE TITLE
Mekanism Fluid Tanks lose contents when transferring to EnderIO Fluid Pipes

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#24]
Placing a filled Fluid Tank (tested with Basic and Advanced) from Mekanism on top of a Fluid Conduid from EnderIO results in the loss of the contents of the tank. 

Tested with Lava and Water. 

Initial placing is fine, but when turning on the conduit (toggling from High redstone to low/disabled), the liquid vanishes.

**Comment by utoc** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3722

**Comment by utoc** [comment]
Bug with Mekanism, on hold on Aiden gets back to coding

**Comment by utoc** [comment]
Issue fixed in newest release of EIO
