### ISSUE TITLE
PRC will not craft HDPE Pellets when it has Two Speed Upgrades

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#25]
When crafting HDPE Pellets in a PRC, placing a second Speed Upgrade will stop it from working. 

Crafting Substrate and the Substrate multiplication works just fine with 2-3 speed upgrades.

**Comment by utoc** [comment]
This makes NO sense

**Comment by Minithra** [comment]
I'll try more speed upgrades, see if it makes any difference. Will also test it in ssp.

**Comment by Minithra** [comment]
Confirmed in SSP. As soon as the second speed upgrade is added, it stops working. I went up to 8, there was only a little bit of progress as each upgrade was "processed," the PRC didn't work further.

**Comment by utoc** [comment]
This one will be on hold until Aiden gets back to coding.
