### ISSUE TITLE
StorageDrawers / StorageNetwork turning Quite Clear Glass into Vanilla Glass

### ISSUE THREAD

**Issue by Minithra** [utoc/BBQBugs#26]
When placing Quite Clear Glass in storage through the Item Request Table, it pushes the glass in the Vanilla Glass drawer, turning it back into glass. 

Quite Clear Glass - #4968/1 
OreDictionary:
 -fusedGlass
 -blockGlasscolorless
 -blockGlass
enderio:blockFusedQuartz

Glass - # 0020
OreDictionary:
 -blockGlasscolorless
 -blockGlass
minecraft:glass

I'm guessing it's the compatibility in the ore-dictionary that's causing it?

By making and locking a drawer with Quite Clear Glass, I solved it, I think. Both types go where they should when added through the ITem Request Table.

**Comment by utoc** [comment]
This has been corrected
