### ISSUE TITLE
Ender IO Vat Recipes

### ISSUE THREAD

**Issue by Shadow3641** [utoc/BBQBugs#27]
When you click on the hidden button where the recipes but normally is it crashes the game.
Crash Report
http://pastebin.com/ENS1prsd

**Comment by Shadow3641** [comment]
Does this also if you try and look at a recipe in JEI also

**Comment by utoc** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3737

Looks like JEI update broke this.  So.  Soon(tm)

**Comment by utoc** [comment]
Is this still an issue?

**Comment by Shadow3641** [comment]
all fixed
