### ISSUE TITLE
Server crash when adding Heater to Forestry Greenhouse multiblock

### ISSUE THREAD

**Issue by Havanacus** [utoc/BBQBugs#29]
Pastebin of my Client's logs: http://pastebin.com/ugCe63b8

Built a Forestry Greenhouse.
Seemed to work, could open GUI.
Replaced a glass block with a Heater.
Server Crash immediately on Heater placement.

Coordinates are probably x=520.46, y=79.00, z=1134.42
if I'm reading the log correctly.

**Comment by Havanacus** [comment]
It was fixed several versions ago:  https://github.com/ForestryMC/ForestryMC/issues/1414

**Comment by utoc** [comment]
If I update Forestry, I have to disable all forestry rf/T creating devices.  Otherwise crashes.  I'll work on recipes tonight though
