### ISSUE TITLE
Mekanism - Crash Report

### ISSUE THREAD

**Issue by Tellik** [utoc/BBQBugs#3]
This is a different bug than the first Mekanism pipe issue, and seems to be a lot rarer. Similar situation though as the previous mek pipe bug that got fixed, in terms of cause, and what happens. This caused a full crash of the client.

[crash-2016-08-26_21.20.50-client.txt](https://github.com/utoc/BBQBugs/files/440472/crash-2016-08-26_21.20.50-client.txt)

Additional notes: This occurred when I teleported back to base. It seems that the teleport failed and left me half stuck in a wall in my base. Right before it crashed, I could see the unrendered pipes. When I logged in, all was black since I was in the wall.

**Comment by utoc** [comment]
Tellik, reopen this if you get another since the circumstances revolved around an rfTools issue.
