### ISSUE TITLE
Blood Magic Living Armor does not show upgrades when equipped

### ISSUE THREAD

**Issue by Havanacus** [utoc/BBQBugs#33]
Blood Magic 2.1.0-65

Living Chestplate tooltip does not list upgrades when equipped.  Displays normally when in inventory.

We are 1 version behind latest, but the [Changelog](https://github.com/WayofTime/BloodMagic/blob/1.9/changelog.txt) doesn't explicitly mention this fix.

**Comment by utoc** [comment]
https://github.com/WayofTime/BloodMagic/issues/940
