### ISSUE TITLE
Refined Storage solderer stops working

### ISSUE THREAD

**Issue by Havanacus** [utoc/BBQBugs#34]
refinedstorage-1.2-beta4

Setup:  Export bus, Import bus, and Detector connected to solderers to autocraft processors when below a certain level.

Problem:  Occasionally a Solderer stops working.  Removing the items from it's inventory causes to to start working again when new items are exported into it.

Possibly related to: https://github.com/raoulvdberge/refinedstorage/issues/423
May be caused by chunks unloading or server resetting.

**Comment by utoc** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/370

**Comment by Havanacus** [comment]
Another one froze.  Had previously been disabled by redstone, so can't confirm if it was triggered by chunk unloading.

Attempted to fix with block updates:
1: Broke Exporter  -  No change
2: Placed redstone block were Exporter was  -  No change
3: Broke redstone block  -  No change
4: Replaced Exporter  -  Solderer resumed operation

**Comment by scalda** [comment]
I have Found after testing as had the same problem on the hermitcraft server and found it to be the claiming of the chunks via ftb utilities, after updating both mods version to the latest release/beta, all i did was unclaimed all chunks break and replace the parts that have broken and then logged off for a bit, then logged in again and then reclaimed and chunkloaded again and all is working as suppose to be, i hope this helps other people out.

**Comment by utoc** [comment]
Thanks for the tip @scalda
