### ISSUE TITLE
getEnclosingMethod Madness

### ISSUE THREAD

**Issue by utoc** [utoc/BBQBugs#36]
The purpose of this ticket is an attempt to find the ultimate cause(s) for the getEnclosingMethod tick lag going on in the main thread.

**Comment by utoc** [comment]
Mods that seem to have a gross effect on getEnclosingMethod.  Tested by removing mod.  Does not make the mod a culprit but it does suggest potential. 
- QChests (Reduction by a third, 33% to 25%)
- RS (Reduction by half, 33% to 16%)
- EnderIO (Reduction by half, 33% to 16%)
- Mekanism (From 33% to 8%)

**Comment by utoc** [comment]
Update on today

Q seems to be directly or indirectly responsible for 11ms of tick time, maybe supplying energy to someone else?

Shadow's base was admin loaded.. Possibly in on it but unsure.  reduction in tick time from 33% to 25%.  This isn't adding up.

Jereman's base unloading brings it from 33% to 25%
Sphysics base unloading 
Tony's base unloading brings no appreciable change to GEM tick time
Havanacus base unloading **33% to 11%**
3Pixel base unloading
D4rks base unloading brings it from **25% to 6%** (with Jeremans disabled?) and **29% to 22%** with no other bases disabled
Qs base unloading
hell base unloading

**Comment by utoc** [comment]
Edit: Admin SSCL chunks found (190 total):

Havanacus 2 (512 1152)
Shadow 49 (-640 224)
3pixel 81 (400, 128)
Woif 49 (-2960, -1760)
UnknownBase 9 (128, 48)

**Comment by DreiPixel** [comment]
those large admin chunk loads are mine. i did them because of Storage Network. i didnt knew how large those networks were :V and btw i should not have any admin loaded chunks in my base :V it should be sphysics base, he is very near my base

edit: it was to prevent Storage Networks shitcode.

**Comment by utoc** [comment]
No worries bb
