### ISSUE TITLE
Some Sound FX repeating until block broken

### ISSUE THREAD

**Issue by Havanacus** [utoc/BBQBugs#5]
Issue noticed on:
- RfTools Elevator
- Deep Resonance Reactor

When block is activate, sound effects loop until the block is broken.  Activating the block again stacks the sound effect.

**Comment by utoc** [comment]
https://github.com/williewillus/Botania/issues/458

**Comment by utoc** [comment]
Should be fixed with https://github.com/williewillus/Botania/commit/7eb9a89ef4abfeaf3d7131be3a73c5930996d2e6
