### ISSUE TITLE
Forestry Multifarms don't respond to Redstone

### ISSUE THREAD

**Issue by Havanacus** [utoc/BBQBugs#6]
Forestry Multifarms should disable when redstone is applied to the Farm Control block.  Each side should also be disabled if that face receives a redstone signal.

Farms are completely unresponsive to any signal.  Top, bottom, or side.

Issue already reported by someone else on the Forestry Github:  https://github.com/ForestryMC/ForestryMC/issues/1405

**Comment by Havanacus** [comment]
Nevermind, it looks like it just takes a very long time for it to take effect.

I'm going to test a bit more, but it's probably not an issue.

Edit:  Powering the sides does work as intended, but powering the top or bottom of the Farm Control block has no effect.

**Comment by utoc** [comment]
AFAIK powering from the top and bottom should do nothing, right?

**Comment by Havanacus** [comment]
It used to be the farm would shut down completely if powered from above.  If that's changed or I'm mistaken, it's no big deal.  I just used a bit more redstone paste.

**Comment by utoc** [comment]
We'll leave it be to see what mezz says about it then close if its working as intended.
